spring.application.name=smartstock-backend

server.port=8080


# PostgreSQL Database Configuration

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD} 

# spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/smartstock}
# spring.datasource.username=${DATABASE_USERNAME:postgres}
# spring.datasource.password=${DATABASE_PASSWORD:root}

# JPA / Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# Swagger Configuration

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html


jwt.secret=${JWT_SECRET} - for render
#jwt.secret=${JWT_SECRET:smartstock-local-jwt-secret-key-1234567890abcdef}

# ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
# ollama.model=${OLLAMA_MODEL:gemma3:4b}
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:4200}


llm.base-url=https://api.groq.com/openai/v1
llm.api-key=${LLM_API_KEY}
llm.model=openai/gpt-oss-20b

